experimental_monorepo_root = true

[settings]
auto_install = true

[tools]
# -----------------------------------------------------------------------------
act = "latest"
gh = "latest"
# -----------------------------------------------------------------------------

[tasks.'github:workflow']
description = "Access to GitHub Actions workflow of the package"
dir = "{{cwd}}"
run = [
  "mise //packages/core:github:workflow"
]

[tasks.'github:workflow:validate']
description = "Validate GitHub Actions workflow of the package"
run = [
  "mise //packages/core:github:workflow:validate"
]
