experimental_monorepo_root = true

[settings]
auto_install = true

[tasks."container"]
description = "Get access to container CLI"
run = [
  "docker compose --file ./compose.yml"
]
hide = true

[tasks."container:local"]
description = "Get access to container CLI with local configuration"
run = [
  "mise //:container --file compose.local.yml"
]

[tasks."container:prod"]
description = "Get access to container CLI with production configuration"
run = [
  "mise //:container --file compose.prod.yml"
]