services:
  middleware:
    image: node:22-alpine
    working_dir: /runner
    command: npm run dev
    volumes:
      - ./:/runner
    secrets:
      - middleware-credentials
    env_file:
      - .env
    environment:
      CREDENTIALS_FILE: /run/secrets/middleware-credentials

secrets:
  middleware-credentials:
    file: ./settings/.env.credentials
