# -----------------------------------------------------------------------------
[tasks."start"]
description = "Start production service"
run = [
  "docker compose -f ../../compose.yaml up rtmp-relay"
]

[tasks."stop"]
description = "Stop production service"
run = [
  "docker compose -f ../../compose.yaml down rtmp-relay"
]